CREATE DATABASE QLGV;
GO

USE QLGV;
SET DATEFORMAT DMY;
GO

------ I.1 ------
CREATE TABLE Khoa 
( 
	MaKhoa		VARCHAR(4),
	TenKhoa		VARCHAR(40),
	NgTLap		SMALLDATETIME,
	TrgKhoa		CHAR(4),
	CONSTRAINT PK_Khoa PRIMARY KEY (MaKhoa)
)
GO

CREATE TABLE MonHoc
(
	MaMH		VARCHAR(10),
	TenMH		VARCHAR(40),
	TCLT		TINYINT,
	TCTH		TINYINT,
	MaKhoa		VARCHAR(4),
	CONSTRAINT PK_MonHoc PRIMARY KEY (MaMH)
)
GO

CREATE TABLE DieuKien 
(
	MaMH		VARCHAR(10),
	MaMH_Truoc	VARCHAR(10),
	CONSTRAINT PK_DieuKien PRIMARY KEY (MaMH, MaMH_Truoc)
)
GO

CREATE TABLE GiaoVien
(
	MaGV		CHAR(4),
	HoTen		VARCHAR(40),
	HocVi		VARCHAR(10), 
	HocHam		VARCHAR(10),
	GioiTinh	VARCHAR(3),
	NgSinh		SMALLDATETIME,
	NgVL		SMALLDATETIME,
	HeSo		NUMERIC(4, 2),
	MucLuong	MONEY,
	MaKhoa		VARCHAR(4),
	CONSTRAINT PK_GiaoVien PRIMARY KEY (MaGV)
)
GO

CREATE TABLE Lop
(
	MaLop		CHAR(3),
	TenLop		VARCHAR(40),
	TrgLop		CHAR(5),
	SiSo		TINYINT,
	MaGVCN		CHAR(4),
	CONSTRAINT PK_Lop PRIMARY KEY (MaLop)
)
GO

CREATE TABLE HocVien
(
	MaHV		CHAR(5),
	Ho			VARCHAR(40),
	Ten			VARCHAR(10),
	NgSinh		SMALLDATETIME,
	GioiTinh	VARCHAR(3),
	NoiSinh		VARCHAR(40),
	MaLop		CHAR(3),
	CONSTRAINT PK_HocVien PRIMARY KEY (MaHV)
)
GO

CREATE TABLE GiangDay
(
	MaLop		CHAR(3),
	MaMH		VARCHAR(10),	
	MaGV		CHAR(4), 
	HocKy		TINYINT,
	Nam			SMALLINT, 
	TuNgay		SMALLDATETIME,
	DenNgay		SMALLDATETIME, 
	CONSTRAINT PK_GiangDay PRIMARY KEY (MaLop, MaMH)
)
GO

CREATE TABLE KetQuaThi	
(
	MaHV		CHAR(5),
	MaMH		VARCHAR(10),
	LanThi		TINYINT,
	NgThi		SMALLDATETIME,
	Diem		NUMERIC(4, 2),
	KQua		VARCHAR(10),
	CONSTRAINT PK_KetQuaThi PRIMARY KEY (MaHV, MaMH, LanThi)
)
GO

------ I.1 ------
ALTER TABLE Khoa ADD CONSTRAINT FK_Khoa_GiaoVien FOREIGN KEY (TrgKhoa) REFERENCES GiaoVien(MaGV)

ALTER TABLE MonHoc ADD CONSTRAINT FK_MonHoc_Khoa FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)

ALTER TABLE DieuKien ADD CONSTRAINT FK1_DieuKien_MonHoc FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)
ALTER TABLE DieuKien ADD CONSTRAINT FK2_DieuKien_MonHoc FOREIGN KEY (MaMH_Truoc) REFERENCES MonHoc(MaMH)

ALTER TABLE GiaoVien ADD CONSTRAINT FK_GiaoVien_Khoa FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)

ALTER TABLE Lop ADD CONSTRAINT FK_Lop_HocVien FOREIGN KEY (TrgLop) REFERENCES HocVien(MaHV)
ALTER TABLE Lop ADD CONSTRAINT FK_Lop_GiaoVien FOREIGN KEY (MaGVCN) REFERENCES GiaoVien(MaGV)

ALTER TABLE HocVien ADD CONSTRAINT FK_HocVien_Lop FOREIGN KEY (MaLop) REFERENCES Lop(MaLop)

ALTER TABLE GiangDay ADD CONSTRAINT FK_GiangDay_Lop FOREIGN KEY (MaLop) REFERENCES Lop(MaLop)
ALTER TABLE GiangDay ADD CONSTRAINT FK_GiangDay_MonHoc FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)
ALTER TABLE GiangDay ADD CONSTRAINT FK_GiangDay_GiaoVien FOREIGN KEY (MaGV) REFERENCES GiaoVien(MaGV)

ALTER TABLE KetQuaThi ADD CONSTRAINT FK_KetQuaThi_HocVien FOREIGN KEY (MaHV) REFERENCES HocVien(MaHV)
ALTER TABLE KetQuaThi ADD CONSTRAINT FK_KetQuaThi_MonHoc FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)

------ I.1 ------
ALTER TABLE HocVien ADD GhiChu VARCHAR(20),
						DiemTB FLOAT,
						XepLoai VARCHAR(9)
GO